import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/db";
import { generateApiKey } from "@/lib/api-keys";

// POST /api/auth - Handle user creation/lookup on login
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { walletAddress, email } = body;

    // Validation
    if (!walletAddress || !email) {
      return NextResponse.json(
        { error: "Missing required fields: walletAddress, email" },
        { status: 400 }
      );
    }

    // Normalize wallet address (lowercase for consistency)
    const normalizedWallet = walletAddress.toLowerCase();

    // Check if user already exists
    const existingUser = await prisma.user.findUnique({
      where: { walletAddress: normalizedWallet },
    });

    if (existingUser) {
      // Update last login and email if changed
      const updatedUser = await prisma.user.update({
        where: { id: existingUser.id },
        data: {
          email,
          lastLogin: new Date(),
        },
      });

      return NextResponse.json({
        success: true,
        user: {
          id: updatedUser.id,
          walletAddress: updatedUser.walletAddress,
          email: updatedUser.email,
          apiKey: updatedUser.apiKey,
          lastLogin: updatedUser.lastLogin,
          createdAt: updatedUser.createdAt,
        },
        isNewUser: false,
        message: "User logged in successfully",
      });
    }

    // Create new user
    const newUser = await prisma.user.create({
      data: {
        walletAddress: normalizedWallet,
        email,
        // apiKey is auto-generated by Prisma default(uuid())
      },
    });

    return NextResponse.json({
      success: true,
      user: {
        id: newUser.id,
        walletAddress: newUser.walletAddress,
        email: newUser.email,
        apiKey: newUser.apiKey,
        lastLogin: newUser.lastLogin,
        createdAt: newUser.createdAt,
      },
      isNewUser: true,
      message: "New user created successfully",
    });
  } catch (error) {
    console.error("Auth error:", error);
    return NextResponse.json(
      { error: "Authentication failed" },
      { status: 500 }
    );
  }
}

// GET /api/auth - Get user by wallet or email
export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const walletAddress = searchParams.get("walletAddress");
  const email = searchParams.get("email");
  const apiKey = searchParams.get("apiKey");

  try {
    let user;

    if (apiKey) {
      // Lookup by API key
      user = await prisma.user.findUnique({
        where: { apiKey },
      });
    } else if (walletAddress) {
      // Lookup by wallet address
      user = await prisma.user.findUnique({
        where: { walletAddress: walletAddress.toLowerCase() },
      });
    } else if (email) {
      // Lookup by email
      user = await prisma.user.findUnique({
        where: { email },
      });
    } else {
      return NextResponse.json(
        { error: "Missing search parameter: walletAddress, email, or apiKey" },
        { status: 400 }
      );
    }

    if (!user) {
      return NextResponse.json(
        { error: "User not found" },
        { status: 404 }
      );
    }

    return NextResponse.json({
      success: true,
      user: {
        id: user.id,
        walletAddress: user.walletAddress,
        email: user.email,
        apiKey: user.apiKey,
        lastLogin: user.lastLogin,
        createdAt: user.createdAt,
      },
    });
  } catch (error) {
    console.error("User lookup error:", error);
    return NextResponse.json(
      { error: "User lookup failed" },
      { status: 500 }
    );
  }
}
