import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/db";

// POST /api/auth - Handle user creation/lookup on login
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    let { walletAddress, email } = body;

    // Validation
    if (!email) {
      return NextResponse.json(
        { error: "Missing required field: email" },
        { status: 400 }
      );
    }

    // Normalize email
    const normalizedEmail = email.toLowerCase();

    // Handle wallet address - "pending" or empty means no wallet yet
    const hasWallet = walletAddress && walletAddress !== "" && walletAddress !== "pending";
    const normalizedWallet = hasWallet ? walletAddress.toLowerCase() : null;

    // Check if user exists by email first
    const existingUserByEmail = await prisma.user.findUnique({
      where: { email: normalizedEmail },
    });

    if (existingUserByEmail) {
      // User exists - update wallet if new one is provided
      if (hasWallet && !existingUserByEmail.walletAddress) {
        // User had pending wallet, now connecting real wallet
        const updatedUser = await prisma.user.update({
          where: { id: existingUserByEmail.id },
          data: {
            walletAddress: normalizedWallet,
            lastLogin: new Date(),
          },
        });

        return NextResponse.json({
          success: true,
          user: {
            id: updatedUser.id,
            walletAddress: updatedUser.walletAddress,
            email: updatedUser.email,
            apiKey: updatedUser.apiKey,
            lastLogin: updatedUser.lastLogin,
            createdAt: updatedUser.createdAt,
          },
          isNewUser: false,
          message: "Wallet connected successfully",
        });
      }

      // Return existing user
      return NextResponse.json({
        success: true,
        user: {
          id: existingUserByEmail.id,
          walletAddress: existingUserByEmail.walletAddress,
          email: existingUserByEmail.email,
          apiKey: existingUserByEmail.apiKey,
          lastLogin: existingUserByEmail.lastLogin,
          createdAt: existingUserByEmail.createdAt,
        },
        isNewUser: false,
        message: existingUserByEmail.walletAddress 
          ? "User logged in successfully" 
          : "User exists - please connect wallet to continue",
      });
    }

    // Check if user exists by wallet
    if (hasWallet) {
      const existingUserByWallet = await prisma.user.findUnique({
        where: { walletAddress: normalizedWallet! },
      });

      if (existingUserByWallet) {
        // Update email if changed
        const updatedUser = await prisma.user.update({
          where: { id: existingUserByWallet.id },
          data: {
            email: normalizedEmail,
            lastLogin: new Date(),
          },
        });

        return NextResponse.json({
          success: true,
          user: {
            id: updatedUser.id,
            walletAddress: updatedUser.walletAddress,
            email: updatedUser.email,
            apiKey: updatedUser.apiKey,
            lastLogin: updatedUser.lastLogin,
            createdAt: updatedUser.createdAt,
          },
          isNewUser: false,
          message: "User logged in successfully",
        });
      }
    }

    // Create new user
    const newUser = await prisma.user.create({
      data: {
        walletAddress: normalizedWallet,
        email: normalizedEmail,
        // apiKey is auto-generated by Prisma default(uuid())
      },
    });

    return NextResponse.json({
      success: true,
      user: {
        id: newUser.id,
        walletAddress: newUser.walletAddress,
        email: newUser.email,
        apiKey: newUser.apiKey,
        lastLogin: newUser.lastLogin,
        createdAt: newUser.createdAt,
      },
      isNewUser: true,
      message: hasWallet 
        ? "New user created successfully" 
        : "Account created - please connect wallet to use the arena",
    });
  } catch (error: any) {
    console.error("Auth error:", error);
    
    return NextResponse.json(
      { 
        error: "Authentication failed",
        details: error.message || String(error),
        code: error.code || 'UNKNOWN'
      },
      { status: 500 }
    );
  }
}

// GET /api/auth - Get user by wallet or email
export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const walletAddress = searchParams.get("walletAddress");
  const email = searchParams.get("email");
  const apiKey = searchParams.get("apiKey");

  try {
    let user;

    if (apiKey) {
      user = await prisma.user.findUnique({
        where: { apiKey },
      });
    } else if (walletAddress) {
      user = await prisma.user.findUnique({
        where: { walletAddress: walletAddress.toLowerCase() },
      });
    } else if (email) {
      user = await prisma.user.findUnique({
        where: { email: email.toLowerCase() },
      });
    } else {
      return NextResponse.json(
        { error: "Missing search parameter: walletAddress, email, or apiKey" },
        { status: 400 }
      );
    }

    if (!user) {
      return NextResponse.json(
        { error: "User not found" },
        { status: 404 }
      );
    }

    return NextResponse.json({
      success: true,
      user: {
        id: user.id,
        walletAddress: user.walletAddress,
        email: user.email,
        apiKey: user.apiKey,
        lastLogin: user.lastLogin,
        createdAt: user.createdAt,
      },
    });
  } catch (error) {
    console.error("User lookup error:", error);
    return NextResponse.json(
      { error: "User lookup failed" },
      { status: 500 }
    );
  }
}
